# ============================================
# PERFIL PROD
# Backend corre DENTRO de docker-compose junto a la DB.
# Conecta por nombre de servicio en la red familia-network.
# ============================================

spring.datasource.url=jdbc:postgresql://db:${DB_PORT_IN}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
